"""
agents/executor_agent.py — ExecutorAgent (Persistence Layer)
Stores diagnosis results and formats final output.
"""

import json
import os
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

from core.models import DiagnosisReport

console = Console()


class ExecutorAgent:
    """
    Handles persistence and formatted output of diagnosis reports.
    
    Responsibilities:
      - Save results to SQLite
      - Pretty-print results to terminal
      - Return structured report
    """

    def __init__(self):
        self.db = self._init_db()

    def _init_db(self):
        """Initialize SQLite database connection."""
        try:
            from db.database import Database
            return Database()
        except Exception as e:
            console.print(f"[yellow]⚠️  Database init failed: {e} — results won't be saved[/yellow]")
            return None

    def execute(self, report: DiagnosisReport) -> DiagnosisReport:
        """
        Finalize the report: save to DB and print to console.
        
        Args:
            report: Complete DiagnosisReport from pipeline
            
        Returns:
            Same report (with any storage metadata added)
        """
        console.print(f"\n[bold cyan]💾 ExecutorAgent[/bold cyan] — Saving and presenting results...")

        # Set timestamp
        report.timestamp = datetime.utcnow().isoformat()

        # Save to database
        if self.db:
            try:
                self.db.save_report(report)
                console.print("[dim]  ✅ Saved to database[/dim]")
            except Exception as e:
                console.print(f"[dim]  ⚠️  DB save failed: {e}[/dim]")
                report.pipeline_errors.append(f"DB save failed: {e}")

        # Print final report
        self._print_report(report)

        return report

    def _print_report(self, report: DiagnosisReport):
        """Render a rich, formatted report to the terminal."""
        console.print()

        # ── Header ─────────────────────────────────────────────────────
        console.rule("[bold magenta]🧠 ExplainDeFi — Diagnosis Report[/bold magenta]")
        console.print()

        # ── Transaction Info ────────────────────────────────────────────
        info_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
        info_table.add_column("Key", style="dim", width=16)
        info_table.add_column("Value")

        if report.tx_data:
            info_table.add_row("Tx Hash", report.tx_hash)
            info_table.add_row("From", report.tx_data.from_address)
            info_table.add_row("Function", report.tx_data.function_name or "Unknown")
            info_table.add_row(
                "Gas",
                f"{report.tx_data.gas_used:,} / {report.tx_data.gas_limit:,}"
            )
            info_table.add_row("Block", str(report.tx_data.block_number))

        console.print(Panel(info_table, title="[bold]Transaction Info[/bold]", border_style="blue"))

        # ── Failure Diagnosis ───────────────────────────────────────────
        if report.diagnosis:
            d = report.diagnosis
            category_colors = {
                "GAS": "red",
                "BALANCE": "yellow",
                "SLIPPAGE": "magenta",
                "ACCESS": "blue",
                "LOGIC": "cyan",
                "DEADLINE": "orange3",
                "UNKNOWN": "white",
            }
            color = category_colors.get(d.category, "white")

            diag_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
            diag_table.add_column("Key", style="dim", width=16)
            diag_table.add_column("Value")
            diag_table.add_row("Category", f"[{color}]{d.category}[/{color}]")
            diag_table.add_row("Sub-type", d.sub_type)
            diag_table.add_row("Raw Error", d.raw_error or "None")
            diag_table.add_row("Confidence", f"{d.confidence * 100:.0f}%")

            console.print(Panel(
                diag_table,
                title=f"[bold]Failure Diagnosis [{color}]{d.category}[/{color}][/bold]",
                border_style=color,
            ))

        # ── AI Explanation ──────────────────────────────────────────────
        if report.explanation:
            e = report.explanation

            explanation_text = f"[white]{e.explanation}[/white]\n"

            if e.fix_steps:
                explanation_text += "\n[bold green]How to Fix:[/bold green]\n"
                for i, step in enumerate(e.fix_steps, 1):
                    explanation_text += f"  {i}. {step}\n"

            if e.technical_summary:
                explanation_text += f"\n[dim]Technical: {e.technical_summary}[/dim]"

            explanation_text += f"\n\n[dim]Generated by: {e.llm_provider} | Confidence: {e.confidence * 100:.0f}%[/dim]"

            console.print(Panel(
                explanation_text,
                title="[bold]🤖 AI Explanation[/bold]",
                border_style="green",
            ))

        # ── Pipeline Errors (if any) ────────────────────────────────────
        if report.pipeline_errors:
            console.print(f"\n[yellow]⚠️  Pipeline warnings:[/yellow]")
            for err in report.pipeline_errors:
                console.print(f"  [dim]- {err}[/dim]")

        console.rule()
        console.print()
